// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">My Appp</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
import React from "react";

const Home = () => {
  if (process.browser) {
    function sleep(delay) {
      return new Promise((resolve) => {
        setTimeout(resolve, delay);
      });
    }

    function logText(message, isError) {
      if (isError) console.error(message);
      else console.log(message);

      const p = document.createElement("p");
      if (isError) p.setAttribute("class", "error");
      document.querySelector("#output").appendChild(p);
      p.appendChild(document.createTextNode(message));
    }

    function logError(message) {
      logText(message, true);
    }

    function setShareButtonsEnabled(enabled) {
      document.querySelector("#share").disabled = !enabled;
      document.querySelector("#share-no-gesture").disabled = !enabled;
    }

    function checkboxChanged(e) {
      const checkbox = e.target;
      const textfield = document.querySelector("#" + checkbox.id.split("_")[0]);

      textfield.disabled = !checkbox.checked;
      if (!checkbox.checked) textfield.value = "";
    }

    function checkBasicFileShare() {
      // XXX: There is no straightforward API to do this.
      // For now, assume that text/plain is supported everywhere.
      const txt = new Blob(["Hello, world!"], { type: "text/plain" });
      // XXX: Blob support? https://github.com/w3c/web-share/issues/181
      const file = new File([txt], "test.txt");
      return navigator.canShare({ files: [file] });
    }

    async function testWebShare() {
      const title_input = document.querySelector("#title");
      const text_input = document.querySelector("#text");
      const url_input = document.querySelector("#url");
      /** @type {HTMLInputElement} */
      // const file_input = document.querySelector("#files");
const file_input = "https://picsum.photos/200/300"
      const title = title_input.disabled ? undefined : title_input.value;
      const text = text_input.disabled ? undefined : text_input.value;
      const url = url_input.disabled ? undefined : url_input.value;
      const files = file_input.disabled ? undefined : file_input.files;

      if (files && files.length > 0) {
        if (!navigator.canShare) {
          logError(
            "Warning: canShare is not supported. File sharing may not be supported at all."
          );
        } else if (!checkBasicFileShare()) {
          logError("Error: File sharing is not supported in this browser.");
          setShareButtonsEnabled(true);
          return;
        } else if (!navigator.canShare({ files })) {
          logError("Error: share() does not support the given files");
          for (const file of files) {
            logError(
              `File info: name - ${file.name}, size ${file.size}, type ${file.type}`
            );
          }
          setShareButtonsEnabled(true);
          return;
        }
      }

      setShareButtonsEnabled(false);
      try {
        // console.log(window.navigator.share);
        await navigator.share({ files, title, text, url });
        logText("Successfully sent share");
      } catch (error) {
        logError("Error sharing: " + error);
      }
      setShareButtonsEnabled(true);
    }

    async function testWebShareDelay() {
      setShareButtonsEnabled(false);
      await sleep(6000);
      testWebShare();
    }

    function onLoad() {
      // Checkboxes disable and delete textfields.
      document
        .querySelector("#title_checkbox")
        .addEventListener("click", checkboxChanged);
      document
        .querySelector("#text_checkbox")
        .addEventListener("click", checkboxChanged);
      document
        .querySelector("#url_checkbox")
        .addEventListener("click", checkboxChanged);

      //document.querySelector("#share").addEventListener("click", testWebShare);
      document
        .querySelector("#share-no-gesture")
        .addEventListener("click", testWebShareDelay);

        console.log(navigator.share);
        console.log(window.location.protocol);
      if (window.navigator.share === undefined) {
        setShareButtonsEnabled(false);
        if (window.location.protocol === "http:") {
          // navigator.share() is only available in secure contexts.
          window.location.replace(
            window.location.href.replace(/^http:/, "https:")
          );
        } else {
          logError(
            "Error: You need to use a browser that supports this draft " +
              "proposal."
          );
        }
      }
    }

    window.addEventListener("load", onLoad);
  }
  return (
    <>
      <table>
        <tr>
          <td>Title:</td>
          <td>
            <input type="checkbox" id="title_checkbox"  />
          </td>
          <td>
            <input id="title" value="The Title" size="40" />
          </td>
        </tr>
        <tr>
          <td>Text:</td>
          <td>
            <input type="checkbox" id="text_checkbox"  />
          </td>
          <td>
            <input id="text" value="The message" size="40" />
          </td>
        </tr>
        <tr>
          <td>URL:</td>
          <td>
            <input type="checkbox" id="url_checkbox"  />
          </td>
          <td>
            <input id="url" value="https://example.com" size="40" />
          </td>
        </tr>
        {/* <tr>
          <td>Files:</td>
          <td></td>
          <td>
            <input id="files" type="file" multiple />
          </td>
        </tr> */}
      </table>
      <p>
        <input id="share" type="button" value="Share" />{" "}
        <input
          id="share-no-gesture"
          type="button"
          value="Share without user gesture"
        />
      </p>
      <div id="output"></div>
      <p>
        This is a test page for the{" "}
        <a href="https://w3c.github.io/web-share/">Web Share API</a>,
        demonstrating
        <a href="https://w3c.github.io/web-share/#dom-sharedata-files">file</a>
        sharing. It only works in browsers that have implemented file sharing.
      </p>
    </>
  );
};

export default Home;
