// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">My Appp</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
// import React from "react";

import React from 'react';
import html2canvas from "html2canvas";
import Image from 'next/image'

// interface IWebShareImageProps {}

// async function onShare() {
//   const response = await fetch('nacho.jpg');
//   const blob = await response.blob();
//   const filesArray: File[] = [new File([blob], 'meme.jpg', { type: "image/jpeg", lastModified: new Date().getTime() })];
//   const shareData = {
//     files: filesArray,
//   };
//   navigator.share(shareData as any).then(() => {
//     console.log('Shared successfully');
//   })
// }

// function WebShareImage({}: IWebShareImageProps): JSX.Element {
//   return (
//     <div className="exampleContents">
//       <h1>Sharing an Image</h1>
//       <img src="nacho.jpg" alt='Nacho Libre saying "take it easy"' />
//       <button className="pure-button pure-button-primary share-button" onClick={onShare}>Share Image</button>
//       <a href="https://github.com/benkaiser/web-share-images/blob/master/src/examples/WebShareImage.tsx" className="pure-button share-button">View Code</a>
//     </div>
//   );
// }

// export default WebShareImage;

const Home = () => {
  //interface IWebShareImageProps {}
  const onShare = async () => {

    ///creating images
    const element = document.getElementById("capture");
    const canvas = await html2canvas(element, { useCORS: true });

    const data = canvas.toDataURL("image/jpg");
    // const link = document.createElement("a");
    //  const response = await fetch(data);
    //  const blob = await response.blob();
    //  console.log(blob)
    // if (typeof link.download === "number") {
    //   console.log(data);
    //   link.href = data;
    //   link.download = "image.jpg";

    //   document.body.appendChild(link);
    //   link.click();
    //   document.body.removeChild(link);
    // } else {
    //   window.open(data);
    // }


    const response = await fetch(data);
    const blob = await response.blob();
    console.log(blob);
    const filesArray = [
      new File(
        [blob],
        'meme.jpg',
        {
          type: "image/jpeg",
          lastModified: new Date().getTime()
        }
      )
    ];
    console.log(filesArray)
    const shareData = {
      files: filesArray,
    };
    try {
      // console.log(window.navigator.share);
     // await navigator.share({ files, title, text, url });
      await navigator.share(shareData);
      console.log("Successfully sent share");
    } catch (error) {
      console.log("Error sharing: " + error);
    }
  }
  return (
    <>
      <div className='exampleContents'>
        <h1>Sharing an Image in whats app</h1>
      </div>
      <div className="card" id="capture">
        <img className="card-img-top" src="https://picsum.photos/200/300" alt="Card image cap" />

        <div className="card-body">
          <h5 className="card-title">Card title</h5>
          <p className="card-text">avadhsfasflk;as  fsfjasklfj klfjklasjfjasl</p>
          <a href="#" className="btn btn-primary">Go somewhere</a>
        </div>
      </div>
      <button className="pure-button pure-button-primary share-button" onClick={onShare}>Share Image</button>
    </>
  )
}

export default Home;